#!/usr/bin/env python3

"""
cookiesnook - export cookies from browser
2022, ed <irc.rizon.net>, MIT-licensed, https://github.com/9001/usr-local-bin
"""

import os
import re
import sys
import tempfile

try:
    from yt_dlp import cookies as Cookies
except:
    t = "\033[1;31m\n\n  need yt_dlp; please run the following:\n    {} -m pip install --user -U yt_dlp\n\033[0m"
    raise Exception(t.format(sys.executable))


def main():
    ptn = None
    try:
        browser, fn = sys.argv[1:3]
    except:
        blt = ",".join(list(sorted(Cookies.SUPPORTED_BROWSERS)))
        t = """
need arg 1: browser [{}]
need arg 2: output filename or -
optional arg 3: regex of domains to include

example:
  csnk firefox - ^.youtube.com
"""
        print(t.format(blt))
        return 1

    if len(sys.argv) > 3:
        ptn = re.compile("^$|^#|" + sys.argv[3])

    cj = Cookies.extract_cookies_from_browser(browser)
    with tempfile.TemporaryDirectory() as td:
        fp = os.path.join(td, "a")
        cj.save(fp)
        with open(fp, "rb") as f:
            txt = f.read()

        if ptn:
            txt = txt.decode("utf-8", "ignore").split("\n")
            txt = [x for x in txt if ptn.search(x)]
            txt = "\n".join(txt).encode("ascii")

        if fn == "-":
            sys.stdout.buffer.write(txt + b"\n")
        else:
            with open(fn, "wb") as f:
                f.write(txt)


if __name__ == "__main__":
    sys.exit(main() or 0)
