#!/bin/bash
set -e

# ileave - interleave two files
# ed <irc.rizon.net> MIT-licensed

f1="$1"
f2="$2"
[ ! -z "$f2" ] ||
{
	printf 'need arg 1:  file 1\n'
	printf 'need arg 2:  file 2\n'
	exit 1
}

p=1
p2=0
split=32
nsplit=''

end()
{
	stty echo
}
trap end EXIT
stty -echo

getsize()
{	
	sw=$(tput cols)
	sh=$(tput lines)
}

draw()
{
	printf '\033[H\033[31mh/u\033[0m scroll, \033[31mj/i\033[0m pgup/pgdn, \033[31mk/o\033[0m offset, \033[31mUPPERCASE\033[0m x10' "$f1" "$f2"
	{
		cat -n -- "$f1" | tr '\t' ' '
		tr '\0' '\n' < /dev/zero
	} |
	tail -n +$p |
	head -n $(((sh-2)/3)) |
	LC_ALL=en_US.UTF-8 gawk '{
		printf "\n\nL%s\033[K\n", substr($0,1,'$sw')
	}'
	
	printf '\033[J\033[H'
	{
		cat -n -- "$f2" | tr '\t' ' '
		tr '\0' '\n' < /dev/zero
	} |
	tail -n +$((p+p2)) |
	head -n $(((sh-2)/3)) |
	LC_ALL=en_US.UTF-8 gawk '{
		printf "\n\033[K\n\nR%s\033[K", substr($0,1,'$sw')
	}'
	
	printf '\033[1;54H'
}

clear
getsize
draw

while true
do
	read -u1 -n1 -r
	lc="$(
		printf '%s\n' "$REPLY" |
		tr '[:upper:]' '[:lower:']
	)"
	
	step=1
	[ "$REPLY" == "$lc" ] ||
		step=10
	
	getsize

	case "$lc" in
	h)
		p=$((p+$step))
		;;
	u)
		p=$((p-$step))
		[ $p -le 0 ] && p=1
		;;
	j)
		p=$((p+((sh-2)/3)))
		;;
	i)
		p=$((p-((sh-2)/3)))
		[ $p -le 0 ] && p=1
		;;
	k)
		p2=$((p2+$step))
		;;
	o)
		p2=$((p2-$step))
		;;
	q)
		exit 0
		;;
	esac
	
	[ ! -z "$nsplit" ] &&
	{
		split=$((split+nsplit))
		nsplit=''
		gensplit
	}
	
	draw
done
