#!/bin/bash
cd ~/Pictures/ss/; while true; do sleep 3; find -maxdepth 1 -type f -iname Screenshot_\* -printf '%T@ %s %p\n' | sort -n | tail -n 1 | while IFS=' ' read -r ts sz png; do ext="${png##*.}"; jpg="${png%.*}.jpg"; [[ "$ext" == "png" ]] || continue; [[ $sz -gt 1024000 ]] || continue; printf '%s  %s\n' $(date +%Y-%m%d-%H%M%S) "$png"; convert -quality 80% "$png" "$jpg"; done; done

