#!/bin/bash
set -e

# uopen - mount a LUKS-encrypted drive
# ed <irc.rizon.net> MIT-licensed

rmdir /mnt/*_ov >/dev/null 2>/dev/null || true

while read dev size
do
	ov="${dev}_ov"

	[[ -e "/dev/mapper/${ov}" ]] &&
		continue
	
	printf '\nmount %s (%s) [y/n] ' "$dev" "$size"
	while true
	do
		read -n1 -u1 -r
		#printf '[%s]\n' "$REPLY"
		printf '%s\n' "$REPLY" | grep -qE '^[yYnN]$' || continue
		printf '%s\n' "$REPLY" | grep -qE '^[yY]$' &&
			act=1 || act=''
		break
	done
	echo
	[[ $act ]] ||
		continue

	printf 'passphrase> '
	read -u1 -rs
	{
		printf '%s' "$REPLY" |
		cryptsetup luksOpen /dev/"$dev" "$ov"

		mkdir -p /mnt/"$ov"
		mount /dev/mapper/"$ov" /mnt/"$ov"
	} &

done < <(
	lsblk -o KNAME,FSTYPE,size |
	awk '$2=="crypto_LUKS" {print $1, $3}'
)
echo ok
